security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator
            http_basic: ~
            entry_point: http_basic
            lazy: true
            provider: app_user_provider


    access_control:
            - { path: ^/api/create-account, roles: PUBLIC_ACCESS }
            - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
        # - { path: ^/profile, roles: ROLE_USER }
